---
language: ruby
bundler_args: --without development
before_install:
 - rm Gemfile.lock || true
 - curl getpuppet.whilefork.com | sudo bash
 - puppet module build
 - sudo puppet module install pkg/zleslie-bacula-*.tar.gz
rvm:
  - 2.0.0
  - 2.1.0
script:
  - bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
